import fs from "node:fs/promises";
import path from "node:path";
import { getLogger } from "../utils/logger.js";
import type { AppConfig, AnalysisResult, StackFrame } from "../types/index.js";

/**
 * Generates Markdown diagnostic reports from analysis results.
 */
export class ReportGenerator {
  private reportDir: string;

  constructor(config: AppConfig) {
    this.reportDir = config.reportDir;
  }

  /**
   * Generate a Markdown report file. Returns the file path.
   */
  async generate(result: AnalysisResult): Promise<string> {
    const logger = getLogger();

    const fileName = this.createFileName(result);
    const filePath = path.join(this.reportDir, fileName);
    const content = this.renderMarkdown(result);

    await fs.writeFile(filePath, content, "utf-8");
    logger.info({ filePath }, "Report generated");

    return filePath;
  }

  /**
   * Build report file name from timestamp + error type.
   * Example: 2026-02-21T15-02-06_ECONNREFUSED.md
   */
  private createFileName(result: AnalysisResult): string {
    const timestamp = new Date()
      .toISOString()
      .replace(/[:.]/g, "-")
      .slice(0, 19);
    const errorType = result.parsedError.errorType
      .replace(/[^a-zA-Z0-9]/g, "_")
      .slice(0, 30);
    return `${timestamp}_${errorType}.md`;
  }

  /**
   * Render the full Markdown report.
   */
  private renderMarkdown(result: AnalysisResult): string {
    const { errorBlock, parsedError, diagnosis } = result;

    const severityEmoji: Record<string, string> = {
      critical: "🔴",
      high: "🟠",
      medium: "🟡",
      low: "🟢",
    };

    const emoji = severityEmoji[parsedError.severity] ?? "⚪";

    return `# ${emoji} Error Diagnostic Report

**Generated:** ${new Date().toISOString()}
**Source:** \`${errorBlock.source}\`
**Severity:** ${parsedError.severity.toUpperCase()}
**Confidence:** ${diagnosis.confidence}%
**Error ID:** \`${errorBlock.id}\`

---

## Error Summary

**${parsedError.errorType}:** ${parsedError.errorMessage}

## Context

\`\`\`
${errorBlock.contextLines.join("\n")}
\`\`\`

## Stack Trace

${this.renderStackFrames(parsedError.stackFrames)}

## Root Cause Analysis

${diagnosis.explanation}

**Root Cause:** ${diagnosis.rootCause}

## Proposed Fix

${diagnosis.suggestedFix.description}

\`\`\`${diagnosis.suggestedFix.language}
${diagnosis.suggestedFix.fixed}
\`\`\`

${diagnosis.suggestedFix.filePath ? `**File:** \`${diagnosis.suggestedFix.filePath}\`\n` : ""}
${diagnosis.additionalNotes.length > 0 ? `## Additional Notes\n\n${diagnosis.additionalNotes.map((n) => `- ${n}`).join("\n")}\n` : ""}
---

*Generated by [ALAA](https://github.com/alaa) — Agentic Log Analyzer & Auto-Fixer*
`;
  }

  /**
   * Render stack frames as a formatted list.
   */
  private renderStackFrames(frames: StackFrame[]): string {
    if (frames.length === 0) {
      return "_No stack frames available._\n";
    }

    return frames
      .map(
        (f, i) =>
          `${i + 1}. \`${f.functionName}\` at \`${f.file}:${f.line}\`${f.code ? `\n   \`\`\`\n   ${f.code}\n   \`\`\`` : ""}`
      )
      .join("\n");
  }
}
